"""country name unique and not null

Revision ID: 1d727c566d84
Revises: 144ddb23f306
Create Date: 2026-03-30 20:47:53.304712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d727c566d84'
down_revision: Union[str, Sequence[str], None] = '144ddb23f306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_country_name', ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_constraint('uq_country_name', type_='unique')

    # ### end Alembic commands ###
