"""create profile

Revision ID: 2342533cf343
Revises: 
Create Date: 2026-03-30 20:39:15.430431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2342533cf343'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('birth_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('\n            (\n                birth_year IS NULL OR \n                birth_month IS NULL OR \n                birth_day IS NULL OR\n                (\n                    birth_day <= CASE birth_month\n                        WHEN 1 THEN 31\n                        WHEN 2 THEN (\n                            CASE \n                                WHEN (birth_year % 4 = 0 AND birth_year % 100 != 0) \n                                     OR (birth_year % 400 = 0) \n                                THEN 29 \n                                ELSE 28 \n                            END\n                        )\n                        WHEN 3 THEN 31\n                        WHEN 4 THEN 30\n                        WHEN 5 THEN 31\n                        WHEN 6 THEN 30\n                        WHEN 7 THEN 31\n                        WHEN 8 THEN 31\n                        WHEN 9 THEN 30\n                        WHEN 10 THEN 31\n                        WHEN 11 THEN 30\n                        WHEN 12 THEN 31\n                    END\n                )\n            )\n            ', name='check_valid_date'),
    sa.CheckConstraint('birth_day IS NULL OR (birth_day BETWEEN 1 AND 31)', name='check_birth_day_range'),
    sa.CheckConstraint('birth_month IS NULL OR (birth_month BETWEEN 1 AND 12)', name='check_birth_month_range'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
