"""add clothes and photo_clothes tables

Revision ID: 241f93ab3e7a
Revises: f02077f51f81
Create Date: 2026-04-04 15:36:03.013355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241f93ab3e7a'
down_revision: Union[str, Sequence[str], None] = 'f02077f51f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('material', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_clothes',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('clothes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clothes_id'], ['clothes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id', 'clothes_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_clothes')
    op.drop_table('clothes')
    # ### end Alembic commands ###
