"""add current_location_id to profiles

Revision ID: 4216d26400e7
Revises: b5568024de0f
Create Date: 2026-04-03 19:09:02.533971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4216d26400e7'
down_revision: Union[str, Sequence[str], None] = 'b5568024de0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_location_to_profile", 'locations', ['current_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint("fk_location_to_profile", type_='foreignkey')
        batch_op.drop_column('current_location_id')

    # ### end Alembic commands ###
