"""add cover_url to clothes

Revision ID: 82590d4b2dfc
Revises: 836d5b857c03
Create Date: 2026-04-04 16:42:44.911356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82590d4b2dfc'
down_revision: Union[str, Sequence[str], None] = '836d5b857c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
