"""add seasons daytimes events tables

Revision ID: 836d5b857c03
Revises: 396b4b3131d5
Create Date: 2026-04-04 16:30:01.275440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836d5b857c03'
down_revision: Union[str, Sequence[str], None] = '396b4b3131d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daytimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('season_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daytime_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_photos_addresses', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_photos_seasons', 'seasons', ['season_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_photos_events', 'events', ['event_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_photos_daytimes', 'daytimes', ['daytime_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_photos_addresses', type_='foreignkey')
        batch_op.drop_constraint('fk_photos_seasons', type_='foreignkey')
        batch_op.drop_constraint('fk_photos_events', type_='foreignkey')
        batch_op.drop_constraint('fk_photos_daytimes', type_='foreignkey')
        batch_op.drop_column('address_id')
        batch_op.drop_column('event_id')
        batch_op.drop_column('daytime_id')
        batch_op.drop_column('season_id')
        batch_op.drop_column('rating')

    op.drop_table('seasons')
    op.drop_table('events')
    op.drop_table('daytimes')
    # ### end Alembic commands ###
