"""delete address_id from photo

Revision ID: 8ef1a8f850a5
Revises: 0e26d5a866a8
Create Date: 2026-04-11 13:19:14.041485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef1a8f850a5'
down_revision: Union[str, Sequence[str], None] = '0e26d5a866a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_photos_addresses'), type_='foreignkey')
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_photos_addresses'), 'addresses', ['address_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
