"""add professions and employments tables

Revision ID: e480450230d1
Revises: d830a7a4e071
Create Date: 2026-04-04 15:08:20.325393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e480450230d1'
down_revision: Union[str, Sequence[str], None] = 'd830a7a4e071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_professions_name'), ['name'], unique=True)

    op.create_table('employments',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'profession_id')
    )
    with op.batch_alter_table('employments', schema=None) as batch_op:
        batch_op.create_index('ix_employments_profile_profession', ['profile_id', 'profession_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employments', schema=None) as batch_op:
        batch_op.drop_index('ix_employments_profile_profession')

    op.drop_table('employments')
    with op.batch_alter_table('professions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professions_name'))
        batch_op.drop_index(batch_op.f('ix_professions_id'))

    op.drop_table('professions')
    # ### end Alembic commands ###
