"""add university to profile

Revision ID: f8dab0c9d7ad
Revises: 8ef1a8f850a5
Create Date: 2026-04-11 16:17:59.454723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8dab0c9d7ad'
down_revision: Union[str, Sequence[str], None] = '8ef1a8f850a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_university_id", 'places', ['university_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint("fk_university_id", type_='foreignkey')
        batch_op.drop_column('university_id')

    # ### end Alembic commands ###
